using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Windows.Forms;

namespace NaviDoctor
{
    public class BattleChipData
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int Quantity { get; set; }

        public BattleChipData()
        {
        }
        
        public static List<BattleChipData> BN1ChipNameMap = new List<BattleChipData>()
        { 
            new BattleChipData { ID = 1, Name = "Cannon" },
            new BattleChipData { ID = 2, Name = "HiCannon" },
            new BattleChipData { ID = 3, Name = "M-Cannon" },
            new BattleChipData { ID = 4, Name = "Sword" },
            new BattleChipData { ID = 5, Name = "WideSwrd" },
            new BattleChipData { ID = 6, Name = "LongSwrd" },
            new BattleChipData { ID = 7, Name = "LilBomb" },
            new BattleChipData { ID = 8, Name = "CrosBomb" },
            new BattleChipData { ID = 9, Name = "BigBomb" },
            new BattleChipData { ID = 10, Name = "Spreader" },
            new BattleChipData { ID = 11, Name = "Bubbler" },
            new BattleChipData { ID = 12, Name = "Heater" },
            new BattleChipData { ID = 13, Name = "MiniBomb" },
            new BattleChipData { ID = 14, Name = "Shotgun" },
            new BattleChipData { ID = 15, Name = "Crossgun" },
            new BattleChipData { ID = 16, Name = "ShokWave" },
            new BattleChipData { ID = 17, Name = "SoniWave" },
            new BattleChipData { ID = 18, Name = "DynaWave" },
            new BattleChipData { ID = 19, Name = "FireTowr" },
            new BattleChipData { ID = 20, Name = "AquaTowr" },
            new BattleChipData { ID = 21, Name = "WoodTowr" },
            new BattleChipData { ID = 22, Name = "Quake1" },
            new BattleChipData { ID = 23, Name = "Quake2" },
            new BattleChipData { ID = 24, Name = "Quake3" },
            new BattleChipData { ID = 25, Name = "FireSwrd" },
            new BattleChipData { ID = 26, Name = "ElecSwrd" },
            new BattleChipData { ID = 27, Name = "AquaSwrd" },
            new BattleChipData { ID = 28, Name = "GutsPnch" },
            new BattleChipData { ID = 29, Name = "IcePunch" },
            new BattleChipData { ID = 30, Name = "FtrSwrd" },
            new BattleChipData { ID = 31, Name = "Dash" },
            new BattleChipData { ID = 32, Name = "KngtSwrd" },
            new BattleChipData { ID = 33, Name = "HeroSwrd" },
            new BattleChipData { ID = 34, Name = "MetGuard" },
            new BattleChipData { ID = 35, Name = "23" },
            new BattleChipData { ID = 36, Name = "24" },
            new BattleChipData { ID = 37, Name = "TriArrow" },
            new BattleChipData { ID = 38, Name = "TriSpear" },
            new BattleChipData { ID = 39, Name = "TriLance" },
            new BattleChipData { ID = 40, Name = "Typhoon" },
            new BattleChipData { ID = 41, Name = "Huricane" },
            new BattleChipData { ID = 42, Name = "Cyclone" },
            new BattleChipData { ID = 43, Name = "Howitzer" },
            new BattleChipData { ID = 44, Name = "Thunder1" },
            new BattleChipData { ID = 45, Name = "Thunder2" },
            new BattleChipData { ID = 46, Name = "Thunder3" },
            new BattleChipData { ID = 47, Name = "2F" },
            new BattleChipData { ID = 48, Name = "30" },
            new BattleChipData { ID = 49, Name = "Snakegg1" },
            new BattleChipData { ID = 50, Name = "Snakegg2" },
            new BattleChipData { ID = 51, Name = "Snakegg3" },
            new BattleChipData { ID = 52, Name = "Hammer" },
            new BattleChipData { ID = 53, Name = "35" },
            new BattleChipData { ID = 54, Name = "36" },
            new BattleChipData { ID = 55, Name = "Bodyburn" },
            new BattleChipData { ID = 56, Name = "38" },
            new BattleChipData { ID = 57, Name = "39" },
            new BattleChipData { ID = 58, Name = "Ratton1" },
            new BattleChipData { ID = 59, Name = "Ratton2" },
            new BattleChipData { ID = 60, Name = "Ratton3" },
            new BattleChipData { ID = 61, Name = "Lockon1" },
            new BattleChipData { ID = 62, Name = "Lockon2" },
            new BattleChipData { ID = 63, Name = "Lockon3" },
            new BattleChipData { ID = 64, Name = "X-Panel1" },
            new BattleChipData { ID = 65, Name = "X-Panel3" },
            new BattleChipData { ID = 66, Name = "42" },
            new BattleChipData { ID = 67, Name = "Recov10" },
            new BattleChipData { ID = 68, Name = "Recov30" },
            new BattleChipData { ID = 69, Name = "Recov50" },
            new BattleChipData { ID = 70, Name = "Recov80" },
            new BattleChipData { ID = 71, Name = "Recov120" },
            new BattleChipData { ID = 72, Name = "Recov150" },
            new BattleChipData { ID = 73, Name = "Recov200" },
            new BattleChipData { ID = 74, Name = "Recov300" },
            new BattleChipData { ID = 75, Name = "4B" },
            new BattleChipData { ID = 76, Name = "Steal" },
            new BattleChipData { ID = 77, Name = "4D" },
            new BattleChipData { ID = 78, Name = "4E" },
            new BattleChipData { ID = 79, Name = "Geddon1" },
            new BattleChipData { ID = 80, Name = "Geddon2" },
            new BattleChipData { ID = 81, Name = "51" },
            new BattleChipData { ID = 82, Name = "Escape" },
            new BattleChipData { ID = 83, Name = "Interupt" },
            new BattleChipData { ID = 84, Name = "LifeAura" },
            new BattleChipData { ID = 85, Name = "AquaAura" },
            new BattleChipData { ID = 86, Name = "FireAura" },
            new BattleChipData { ID = 87, Name = "WoodAura" },
            new BattleChipData { ID = 88, Name = "Repair" },
            new BattleChipData { ID = 89, Name = "59" },
            new BattleChipData { ID = 90, Name = "5A" },
            new BattleChipData { ID = 91, Name = "Cloud" },
            new BattleChipData { ID = 92, Name = "Cloudier" },
            new BattleChipData { ID = 93, Name = "Cloudest" },
            new BattleChipData { ID = 94, Name = "IceCube" },
            new BattleChipData { ID = 95, Name = "RockCube" },
            new BattleChipData { ID = 96, Name = "60" },
            new BattleChipData { ID = 97, Name = "TimeBom1" },
            new BattleChipData { ID = 98, Name = "TimeBom2" },
            new BattleChipData { ID = 99, Name = "TimeBom3" },
            new BattleChipData { ID = 100, Name = "Invis1" },
            new BattleChipData { ID = 101, Name = "Invis2" },
            new BattleChipData { ID = 102, Name = "Invis3" },
            new BattleChipData { ID = 103, Name = "IronBody" },
            new BattleChipData { ID = 104, Name = "68" },
            new BattleChipData { ID = 105, Name = "Remobit1" },
            new BattleChipData { ID = 106, Name = "Remobit2" },
            new BattleChipData { ID = 107, Name = "Remobit3" },
            new BattleChipData { ID = 108, Name = "BstrGard" },
            new BattleChipData { ID = 109, Name = "BstrBomb" },
            new BattleChipData { ID = 110, Name = "BstrSwrd" },
            new BattleChipData { ID = 111, Name = "BstrPnch" },
            new BattleChipData { ID = 112, Name = "RingZap1" },
            new BattleChipData { ID = 113, Name = "RingZap2" },
            new BattleChipData { ID = 114, Name = "RingZap3" },
            new BattleChipData { ID = 115, Name = "Candle1" },
            new BattleChipData { ID = 116, Name = "Candle2" },
            new BattleChipData { ID = 117, Name = "Candle3" },
            new BattleChipData { ID = 118, Name = "SloGauge" },
            new BattleChipData { ID = 119, Name = "FstGauge" },
            new BattleChipData { ID = 120, Name = "78" },
            new BattleChipData { ID = 121, Name = "Drain1" },
            new BattleChipData { ID = 122, Name = "Drain2" },
            new BattleChipData { ID = 123, Name = "Drain3" },
            new BattleChipData { ID = 124, Name = "Mine1" },
            new BattleChipData { ID = 125, Name = "Mine2" },
            new BattleChipData { ID = 126, Name = "Mine3" },
            new BattleChipData { ID = 127, Name = "Gaia1" },
            new BattleChipData { ID = 128, Name = "Gaia2" },
            new BattleChipData { ID = 129, Name = "Gaia3" },
            new BattleChipData { ID = 130, Name = "BblWrap1" },
            new BattleChipData { ID = 131, Name = "BblWrap2" },
            new BattleChipData { ID = 132, Name = "BblWrap3" },
            new BattleChipData { ID = 133, Name = "Wave" },
            new BattleChipData { ID = 134, Name = "RedWave" },
            new BattleChipData { ID = 135, Name = "BigWave" },
            new BattleChipData { ID = 136, Name = "Muramasa" },
            new BattleChipData { ID = 137, Name = "Dropdown" },
            new BattleChipData { ID = 138, Name = "Popup" },
            new BattleChipData { ID = 139, Name = "Dynamyt1" },
            new BattleChipData { ID = 140, Name = "Dynamyt2" },
            new BattleChipData { ID = 141, Name = "Dynamyt3" },
            new BattleChipData { ID = 142, Name = "Anubis" },
            new BattleChipData { ID = 143, Name = "8F" },
            new BattleChipData { ID = 144, Name = "90" },
            new BattleChipData { ID = 145, Name = "IronShld" },
            new BattleChipData { ID = 146, Name = "LeafShld" },
            new BattleChipData { ID = 147, Name = "Barrier" },
            new BattleChipData { ID = 148, Name = "PharoMan" },
            new BattleChipData { ID = 149, Name = "PharoMn2" },
            new BattleChipData { ID = 150, Name = "PharoMn3" },
            new BattleChipData { ID = 151, Name = "ShadoMan" },
            new BattleChipData { ID = 152, Name = "ShadoMn2" },
            new BattleChipData { ID = 153, Name = "ShadoMn3" },
            new BattleChipData { ID = 154, Name = "9A" },
            new BattleChipData { ID = 155, Name = "9B" },
            new BattleChipData { ID = 156, Name = "9C" },
            new BattleChipData { ID = 157, Name = "MagicMan" },
            new BattleChipData { ID = 158, Name = "MagicMn2" },
            new BattleChipData { ID = 159, Name = "MagicMn3" },
            new BattleChipData { ID = 160, Name = "Roll" },
            new BattleChipData { ID = 161, Name = "Roll2" },
            new BattleChipData { ID = 162, Name = "Roll3" },
            new BattleChipData { ID = 163, Name = "GutsMan" },
            new BattleChipData { ID = 164, Name = "GutsMan2" },
            new BattleChipData { ID = 165, Name = "GutsMan3" },
            new BattleChipData { ID = 166, Name = "ProtoMan" },
            new BattleChipData { ID = 167, Name = "ProtoMn2" },
            new BattleChipData { ID = 168, Name = "ProtoMn3" },
            new BattleChipData { ID = 169, Name = "WoodMan" },
            new BattleChipData { ID = 170, Name = "WoodMan2" },
            new BattleChipData { ID = 171, Name = "WoodMan3" },
            new BattleChipData { ID = 172, Name = "FireMan" },
            new BattleChipData { ID = 173, Name = "FireMan2" },
            new BattleChipData { ID = 174, Name = "FireMan3" },
            new BattleChipData { ID = 175, Name = "NumbrMan" },
            new BattleChipData { ID = 176, Name = "NumbrMn2" },
            new BattleChipData { ID = 177, Name = "NumbrMn3" },
            new BattleChipData { ID = 178, Name = "StoneMan" },
            new BattleChipData { ID = 179, Name = "StoneMn2" },
            new BattleChipData { ID = 180, Name = "StoneMn3" },
            new BattleChipData { ID = 181, Name = "IceMan" },
            new BattleChipData { ID = 182, Name = "IceMan2" },
            new BattleChipData { ID = 183, Name = "IceMan3" },
            new BattleChipData { ID = 184, Name = "SkullMan" },
            new BattleChipData { ID = 185, Name = "SkullMn2" },
            new BattleChipData { ID = 186, Name = "SkullMn3" },
            new BattleChipData { ID = 187, Name = "ColorMan" },
            new BattleChipData { ID = 188, Name = "ColorMn2" },
            new BattleChipData { ID = 189, Name = "ColorMn3" },
            new BattleChipData { ID = 190, Name = "BombMan" },
            new BattleChipData { ID = 191, Name = "BombMan2" },
            new BattleChipData { ID = 192, Name = "BombMan3" },
            new BattleChipData { ID = 193, Name = "SharkMan" },
            new BattleChipData { ID = 194, Name = "SharkMn2" },
            new BattleChipData { ID = 195, Name = "SharkMn3" },
            new BattleChipData { ID = 196, Name = "ElecMan" },
            new BattleChipData { ID = 197, Name = "ElecMan2" },
            new BattleChipData { ID = 198, Name = "ElecMan3" },
            new BattleChipData { ID = 199, Name = "Bass" },
            new BattleChipData { ID = 200, Name = "C8" },
            new BattleChipData { ID = 201, Name = "C9" },
            new BattleChipData { ID = 202, Name = "Z-Canon1" },
            new BattleChipData { ID = 203, Name = "Z-Canon2" },
            new BattleChipData { ID = 204, Name = "Z-Canon3" },
            new BattleChipData { ID = 205, Name = "Z-Spread" },
            new BattleChipData { ID = 206, Name = "Z-Raton1" },
            new BattleChipData { ID = 207, Name = "Z-Raton2" },
            new BattleChipData { ID = 208, Name = "Z-Raton3" },
            new BattleChipData { ID = 209, Name = "Z-Arrow" },
            new BattleChipData { ID = 210, Name = "Z-Spear" },
            new BattleChipData { ID = 211, Name = "Z-Lance" },
            new BattleChipData { ID = 212, Name = "O-Canon1" },
            new BattleChipData { ID = 213, Name = "O-Canon2" },
            new BattleChipData { ID = 214, Name = "O-Canon3" },
            new BattleChipData { ID = 215, Name = "O-Spread" },
            new BattleChipData { ID = 216, Name = "O-Raton1" },
            new BattleChipData { ID = 217, Name = "O-Raton2" },
            new BattleChipData { ID = 218, Name = "O-Raton3" },
            new BattleChipData { ID = 219, Name = "O-Arrow" },
            new BattleChipData { ID = 220, Name = "O-Spear" },
            new BattleChipData { ID = 221, Name = "O-Lance" },
            new BattleChipData { ID = 222, Name = "B-Bomb" },
            new BattleChipData { ID = 223, Name = "B-Sword" },
            new BattleChipData { ID = 224, Name = "B-Wave" },
            new BattleChipData { ID = 225, Name = "B-Quake" },
            new BattleChipData { ID = 226, Name = "S-Bomb" },
            new BattleChipData { ID = 227, Name = "S-Sword" },
            new BattleChipData { ID = 228, Name = "S-Wave" },
            new BattleChipData { ID = 229, Name = "S-Quake" },
            new BattleChipData { ID = 230, Name = "PwrCanon" },
            new BattleChipData { ID = 231, Name = "HvyStamp" },
            new BattleChipData { ID = 232, Name = "BgStrait" },
            new BattleChipData { ID = 233, Name = "BloodSuk" },
            new BattleChipData { ID = 234, Name = "Storm" },
            new BattleChipData { ID = 235, Name = "GtsShoot" },
            new BattleChipData { ID = 236, Name = "LifeSavr" },
            new BattleChipData { ID = 237, Name = "2xHero" },
            new BattleChipData { ID = 238, Name = "EE" },
            new BattleChipData { ID = 239, Name = "EF" }
        };

        public static List<BattleChipData> BN2ChipNameMap = new List<BattleChipData>()
        {
            new BattleChipData { ID = 0x1, Name = "Cannon" },
            new BattleChipData { ID = 0x2, Name = "HiCannon" },
            new BattleChipData { ID = 0x3, Name = "M-Cannon" },
            new BattleChipData { ID = 0x4, Name = "Shotgun" },
            new BattleChipData { ID = 0x5, Name = "V-Gun" },
            new BattleChipData { ID = 0x6, Name = "CrossGun" },
            new BattleChipData { ID = 0x7, Name = "Spreader" },
            new BattleChipData { ID = 0x8, Name = "Bubbler" },
            new BattleChipData { ID = 0x9, Name = "Bub-V" },
            new BattleChipData { ID = 0xA, Name = "BubCross" },
            new BattleChipData { ID = 0xB, Name = "BubSprd" },
            new BattleChipData { ID = 0xC, Name = "HeatShot" },
            new BattleChipData { ID = 0xD, Name = "Heat-V" },
            new BattleChipData { ID = 0xE, Name = "HeatCros" },
            new BattleChipData { ID = 0xF, Name = "HeatSprd" },
            new BattleChipData { ID = 0x10, Name = "MiniBomb" },
            new BattleChipData { ID = 0x11, Name = "LilBomb" },
            new BattleChipData { ID = 0x12, Name = "CrosBomb" },
            new BattleChipData { ID = 0x13, Name = "BigBomb" },
            new BattleChipData { ID = 0x14, Name = "TreeBom1" },
            new BattleChipData { ID = 0x15, Name = "TreeBom2" },
            new BattleChipData { ID = 0x16, Name = "TreeBom3" },
            new BattleChipData { ID = 0x17, Name = "Sword" },
            new BattleChipData { ID = 0x18, Name = "WideSwrd" },
            new BattleChipData { ID = 0x19, Name = "LongSwrd" },
            new BattleChipData { ID = 0x1A, Name = "FireSwrd" },
            new BattleChipData { ID = 0x1B, Name = "AquaSwrd" },
            new BattleChipData { ID = 0x1C, Name = "ElecSwrd" },
            new BattleChipData { ID = 0x1D, Name = "FireBlde" },
            new BattleChipData { ID = 0x1E, Name = "AquaBlde" },
            new BattleChipData { ID = 0x1F, Name = "ElecBlde" },
            new BattleChipData { ID = 0x20, Name = "StepSwrd" },
            new BattleChipData { ID = 0x21, Name = "Muramasa" },
            new BattleChipData { ID = 0x22, Name = "CustSwrd" },
            new BattleChipData { ID = 0x23, Name = "Kunai1" },
            new BattleChipData { ID = 0x24, Name = "Kunai2" },
            new BattleChipData { ID = 0x25, Name = "Kunai3" },
            new BattleChipData { ID = 0x26, Name = "Slasher" },
            new BattleChipData { ID = 0x27, Name = "Shockwav" },
            new BattleChipData { ID = 0x28, Name = "Sonicwav" },
            new BattleChipData { ID = 0x29, Name = "Dynawave" },
            new BattleChipData { ID = 0x2A, Name = "Quake1" },
            new BattleChipData { ID = 0x2B, Name = "Quake2" },
            new BattleChipData { ID = 0x2C, Name = "Quake3" },
            new BattleChipData { ID = 0x2D, Name = "GutPunch" },
            new BattleChipData { ID = 0x2E, Name = "ColdPnch" },
            new BattleChipData { ID = 0x2F, Name = "Atk+20" },
            new BattleChipData { ID = 0x30, Name = "Atk+30" },
            new BattleChipData { ID = 0x31, Name = "Navi+40" },
            new BattleChipData { ID = 0x32, Name = "DashAtk" },
            new BattleChipData { ID = 0x33, Name = "Wrecker" },
            new BattleChipData { ID = 0x34, Name = "CannBall" },
            new BattleChipData { ID = 0x35, Name = "DoubNdl" },
            new BattleChipData { ID = 0x36, Name = "TripNdl" },
            new BattleChipData { ID = 0x37, Name = "QuadNdl" },
            new BattleChipData { ID = 0x38, Name = "Trident" },
            new BattleChipData { ID = 0x39, Name = "Ratton1" },
            new BattleChipData { ID = 0x3A, Name = "Ratton2" },
            new BattleChipData { ID = 0x3B, Name = "Ratton3" },
            new BattleChipData { ID = 0x3C, Name = "FireRat" },
            new BattleChipData { ID = 0x3D, Name = "Tornado" },
            new BattleChipData { ID = 0x3E, Name = "Twister" },
            new BattleChipData { ID = 0x3F, Name = "Blower" },
            new BattleChipData { ID = 0x40, Name = "Burner" },
            new BattleChipData { ID = 0x41, Name = "ZapRing1" },
            new BattleChipData { ID = 0x42, Name = "ZapRing2" },
            new BattleChipData { ID = 0x43, Name = "ZapRing3" },
            new BattleChipData { ID = 0x44, Name = "Spice1" },
            new BattleChipData { ID = 0x45, Name = "Spice2" },
            new BattleChipData { ID = 0x46, Name = "Spice3" },
            new BattleChipData { ID = 0x47, Name = "Satelit1" },
            new BattleChipData { ID = 0x48, Name = "Satelit2" },
            new BattleChipData { ID = 0x49, Name = "Satelit3" },
            new BattleChipData { ID = 0x4A, Name = "Yo-Yo1" },
            new BattleChipData { ID = 0x4B, Name = "Yo-Yo2" },
            new BattleChipData { ID = 0x4C, Name = "Yo-Yo3" },
            new BattleChipData { ID = 0x4D, Name = "MagBomb1" },
            new BattleChipData { ID = 0x4E, Name = "MagBomb2" },
            new BattleChipData { ID = 0x4F, Name = "MagBomb3" },
            new BattleChipData { ID = 0x50, Name = "Meteor9" },
            new BattleChipData { ID = 0x51, Name = "Meteor12" },
            new BattleChipData { ID = 0x52, Name = "Meteor15" },
            new BattleChipData { ID = 0x53, Name = "Meteor18" },
            new BattleChipData { ID = 0x54, Name = "Hammer" },
            new BattleChipData { ID = 0x55, Name = "CrsShld1" },
            new BattleChipData { ID = 0x56, Name = "CrsShld2" },
            new BattleChipData { ID = 0x57, Name = "CrsShld3" },
            new BattleChipData { ID = 0x58, Name = "TimeBom1" },
            new BattleChipData { ID = 0x59, Name = "TimeBom2" },
            new BattleChipData { ID = 0x5A, Name = "TimeBom3" },
            new BattleChipData { ID = 0x5B, Name = "LilCloud" },
            new BattleChipData { ID = 0x5C, Name = "MedCloud" },
            new BattleChipData { ID = 0x5D, Name = "BigCloud" },
            new BattleChipData { ID = 0x5E, Name = "Mine" },
            new BattleChipData { ID = 0x5F, Name = "FrntSnsr" },
            new BattleChipData { ID = 0x60, Name = "DblSnsr" },
            new BattleChipData { ID = 0x61, Name = "Remobit1" },
            new BattleChipData { ID = 0x62, Name = "Remobit2" },
            new BattleChipData { ID = 0x63, Name = "Remobit3" },
            new BattleChipData { ID = 0x64, Name = "AquaBall" },
            new BattleChipData { ID = 0x65, Name = "ElecBall" },
            new BattleChipData { ID = 0x66, Name = "HeatBall" },
            new BattleChipData { ID = 0x67, Name = "Geyser" },
            new BattleChipData { ID = 0x68, Name = "LavaDrag" },
            new BattleChipData { ID = 0x69, Name = "GodStone" },
            new BattleChipData { ID = 0x6A, Name = "OldWood" },
            new BattleChipData { ID = 0x6B, Name = "PoisMask" },
            new BattleChipData { ID = 0x6C, Name = "PoisFace" },
            new BattleChipData { ID = 0x6D, Name = "Whirlpl" },
            new BattleChipData { ID = 0x6E, Name = "Blckhole" },
            new BattleChipData { ID = 0x6F, Name = "Guard" },
            new BattleChipData { ID = 0x70, Name = "Barrier" },
            new BattleChipData { ID = 0x71, Name = "PanlOut1" },
            new BattleChipData { ID = 0x72, Name = "PanlOut3" },
            new BattleChipData { ID = 0x73, Name = "LineOut" },
            new BattleChipData { ID = 0x74, Name = "Lance" },
            new BattleChipData { ID = 0x75, Name = "ZeusHamr" },
            new BattleChipData { ID = 0x76, Name = "BrnzFist" },
            new BattleChipData { ID = 0x77, Name = "SilvFist" },
            new BattleChipData { ID = 0x78, Name = "GoldFist" },
            new BattleChipData { ID = 0x79, Name = "VarSwrd" },
            new BattleChipData { ID = 0x7A, Name = "Recov10" },
            new BattleChipData { ID = 0x7B, Name = "Recov30" },
            new BattleChipData { ID = 0x7C, Name = "Recov50" },
            new BattleChipData { ID = 0x7D, Name = "Recov80" },
            new BattleChipData { ID = 0x7E, Name = "Recov120" },
            new BattleChipData { ID = 0x7F, Name = "Recov150" },
            new BattleChipData { ID = 0x80, Name = "Recov200" },
            new BattleChipData { ID = 0x81, Name = "Recov300" },
            new BattleChipData { ID = 0x82, Name = "PanlGrab" },
            new BattleChipData { ID = 0x83, Name = "AreaGrab" },
            new BattleChipData { ID = 0x84, Name = "GrabRvng" },
            new BattleChipData { ID = 0x85, Name = "Geddon1" },
            new BattleChipData { ID = 0x86, Name = "Geddon2" },
            new BattleChipData { ID = 0x87, Name = "Geddon3" },
            new BattleChipData { ID = 0x88, Name = "Catcher" },
            new BattleChipData { ID = 0x89, Name = "Mindbndr" },
            new BattleChipData { ID = 0x8A, Name = "Escape" },
            new BattleChipData { ID = 0x8B, Name = "AirShoes" },
            new BattleChipData { ID = 0x8C, Name = "Repair" },
            new BattleChipData { ID = 0x8D, Name = "Candle1" },
            new BattleChipData { ID = 0x8E, Name = "Candle2" },
            new BattleChipData { ID = 0x8F, Name = "Candle3" },
            new BattleChipData { ID = 0x90, Name = "RockCube" },
            new BattleChipData { ID = 0x91, Name = "Prism" },
            new BattleChipData { ID = 0x92, Name = "Guardian" },
            new BattleChipData { ID = 0x93, Name = "Wind" },
            new BattleChipData { ID = 0x94, Name = "Fan" },
            new BattleChipData { ID = 0x95, Name = "Anubis" },
            new BattleChipData { ID = 0x96, Name = "SloGauge" },
            new BattleChipData { ID = 0x97, Name = "FstGauge" },
            new BattleChipData { ID = 0x98, Name = "FullCust" },
            new BattleChipData { ID = 0x99, Name = "Invis1" },
            new BattleChipData { ID = 0x9A, Name = "Invis2" },
            new BattleChipData { ID = 0x9B, Name = "Invis3" },
            new BattleChipData { ID = 0x9C, Name = "DropDown" },
            new BattleChipData { ID = 0x9D, Name = "PopUp" },
            new BattleChipData { ID = 0x9E, Name = "StoneBod" },
            new BattleChipData { ID = 0x9F, Name = "Shadow1" },
            new BattleChipData { ID = 0xA0, Name = "Shadow2" },
            new BattleChipData { ID = 0xA1, Name = "Shadow3" },
            new BattleChipData { ID = 0xA2, Name = "UnderSht" },
            new BattleChipData { ID = 0xA3, Name = "BblWrap" },
            new BattleChipData { ID = 0xA4, Name = "LeafShld" },
            new BattleChipData { ID = 0xA5, Name = "AquaAura" },
            new BattleChipData { ID = 0xA6, Name = "FireAura" },
            new BattleChipData { ID = 0xA7, Name = "WoodAura" },
            new BattleChipData { ID = 0xA8, Name = "ElecAura" },
            new BattleChipData { ID = 0xA9, Name = "LifeAur1" },
            new BattleChipData { ID = 0xAA, Name = "LifeAur2" },
            new BattleChipData { ID = 0xAB, Name = "LifeAur3" },
            new BattleChipData { ID = 0xAC, Name = "MagLine" },
            new BattleChipData { ID = 0xAD, Name = "LavaLine" },
            new BattleChipData { ID = 0xAE, Name = "IceLine" },
            new BattleChipData { ID = 0xAF, Name = "GrassLne" },
            new BattleChipData { ID = 0xB0, Name = "LavaStge" },
            new BattleChipData { ID = 0xB1, Name = "IceStage" },
            new BattleChipData { ID = 0xB2, Name = "GrassStg" },
            new BattleChipData { ID = 0xB3, Name = "HolyPanl" },
            new BattleChipData { ID = 0xB4, Name = "Jealosy" },
            new BattleChipData { ID = 0xB5, Name = "AntiFire" },
            new BattleChipData { ID = 0xB6, Name = "AntiElec" },
            new BattleChipData { ID = 0xB7, Name = "AntiWatr" },
            new BattleChipData { ID = 0xB8, Name = "AntiDmg" },
            new BattleChipData { ID = 0xB9, Name = "AntiSwrd" },
            new BattleChipData { ID = 0xBA, Name = "AntiNavi" },
            new BattleChipData { ID = 0xBB, Name = "AntiRecv" },
            new BattleChipData { ID = 0xBC, Name = "Atk+10" },
            new BattleChipData { ID = 0xBD, Name = "Fire+40" },
            new BattleChipData { ID = 0xBE, Name = "Aqua+40" },
            new BattleChipData { ID = 0xBF, Name = "Wood+40" },
            new BattleChipData { ID = 0xC0, Name = "Elec+40" },
            new BattleChipData { ID = 0xC1, Name = "Navi+20" },
            new BattleChipData { ID = 0xC2, Name = "Roll" },
            new BattleChipData { ID = 0xC3, Name = "Roll V2" },
            new BattleChipData { ID = 0xC4, Name = "Roll V3" },
            new BattleChipData { ID = 0xC5, Name = "GutsMan" },
            new BattleChipData { ID = 0xC6, Name = "GutsMan V2" },
            new BattleChipData { ID = 0xC7, Name = "GutsMan V3" },
            new BattleChipData { ID = 0xC8, Name = "ProtoMan" },
            new BattleChipData { ID = 0xC9, Name = "ProtoMn V2" },
            new BattleChipData { ID = 0xCA, Name = "ProtoMn V3" },
            new BattleChipData { ID = 0xCB, Name = "AirMan" },
            new BattleChipData { ID = 0xCC, Name = "AirMan V2" },
            new BattleChipData { ID = 0xCD, Name = "AirMan V3" },
            new BattleChipData { ID = 0xCE, Name = "QuickMan" },
            new BattleChipData { ID = 0xCF, Name = "QuickMn V2" },
            new BattleChipData { ID = 0xD0, Name = "QuickMn V3" },
            new BattleChipData { ID = 0xD1, Name = "CutMan" },
            new BattleChipData { ID = 0xD2, Name = "CutMan V2" },
            new BattleChipData { ID = 0xD3, Name = "CutMan V3" },
            new BattleChipData { ID = 0xD4, Name = "ShadoMan" },
            new BattleChipData { ID = 0xD5, Name = "ShadoMn V2" },
            new BattleChipData { ID = 0xD6, Name = "ShadoMn V3" },
            new BattleChipData { ID = 0xD7, Name = "KnightMn" },
            new BattleChipData { ID = 0xD8, Name = "KnghtMn V2" },
            new BattleChipData { ID = 0xD9, Name = "KnghtMn V3" },
            new BattleChipData { ID = 0xDA, Name = "MagnetMn" },
            new BattleChipData { ID = 0xDB, Name = "MagntMn V2" },
            new BattleChipData { ID = 0xDC, Name = "MagntMn V3" },
            new BattleChipData { ID = 0xDD, Name = "FreezeMn" },
            new BattleChipData { ID = 0xDE, Name = "FrzMan V2" },
            new BattleChipData { ID = 0xDF, Name = "FrzMan V3" },
            new BattleChipData { ID = 0xE0, Name = "HeatMan" },
            new BattleChipData { ID = 0xE1, Name = "HeatMan V2" },
            new BattleChipData { ID = 0xE2, Name = "HeatMan V3" },
            new BattleChipData { ID = 0xE3, Name = "ToadMan" },
            new BattleChipData { ID = 0xE4, Name = "ToadMan V2" },
            new BattleChipData { ID = 0xE5, Name = "ToadMan V3" },
            new BattleChipData { ID = 0xE6, Name = "ThunMan" },
            new BattleChipData { ID = 0xE7, Name = "ThunMan V2" },
            new BattleChipData { ID = 0xE8, Name = "ThunMan V3" },
            new BattleChipData { ID = 0xE9, Name = "SnakeMan" },
            new BattleChipData { ID = 0xEA, Name = "SnakeMn V2" },
            new BattleChipData { ID = 0xEB, Name = "SnakeMn V3" },
            new BattleChipData { ID = 0xEC, Name = "GateMan" },
            new BattleChipData { ID = 0xED, Name = "GateMan V2" },
            new BattleChipData { ID = 0xEE, Name = "GateMan V3" },
            new BattleChipData { ID = 0xEF, Name = "PlanetMn" },
            new BattleChipData { ID = 0xF0, Name = "PlnetMn V2" },
            new BattleChipData { ID = 0xF1, Name = "PlnetMn V3" },
            new BattleChipData { ID = 0xF2, Name = "NapalmMn" },
            new BattleChipData { ID = 0xF3, Name = "NaplmMn V2" },
            new BattleChipData { ID = 0xF4, Name = "NaplmMn V3" },
            new BattleChipData { ID = 0xF5, Name = "PharoMan" },
            new BattleChipData { ID = 0xF6, Name = "PharoMn V2" },
            new BattleChipData { ID = 0xF7, Name = "PharoMn V3" },
            new BattleChipData { ID = 0xF8, Name = "Bass" },
            new BattleChipData { ID = 0xF9, Name = "Bass V2" },
            new BattleChipData { ID = 0xFA, Name = "Bass V3" },
            new BattleChipData { ID = 0xFB, Name = "BgRedWav" },
            new BattleChipData { ID = 0xFC, Name = "FreezBom" },
            new BattleChipData { ID = 0xFD, Name = "Sparker" },
            new BattleChipData { ID = 0xFE, Name = "GaiaSwrd" },
            new BattleChipData { ID = 0xFF, Name = "BlkBomb" },
            new BattleChipData { ID = 0x100, Name = "FtrSword" },
            new BattleChipData { ID = 0x101, Name = "KngtSwrd" },
            new BattleChipData { ID = 0x102, Name = "HeroSwrd" },
            new BattleChipData { ID = 0x103, Name = "Meteors" },
            new BattleChipData { ID = 0x104, Name = "Poltrgst" },
            new BattleChipData { ID = 0x105, Name = "FireGspl" },
            new BattleChipData { ID = 0x106, Name = "AquaGspl" },
            new BattleChipData { ID = 0x107, Name = "ElecGspl" },
            new BattleChipData { ID = 0x108, Name = "WoodGspl" },
            new BattleChipData { ID = 0x109, Name = "GateSP" },
            new BattleChipData { ID = 0x10A, Name = "10A" },
            new BattleChipData { ID = 0x10B, Name = "10B" },
            new BattleChipData { ID = 0x10C, Name = "10C" },
            new BattleChipData { ID = 0x10D, Name = "10D" },
            new BattleChipData { ID = 0x10E, Name = "Snctuary" },
            new BattleChipData { ID = 0x10F, Name = "10F" },
            new BattleChipData { ID = 0x110, Name = "Z-Canon1" },
            new BattleChipData { ID = 0x111, Name = "Z-Canon2" },
            new BattleChipData { ID = 0x112, Name = "Z-Canon3" },
            new BattleChipData { ID = 0x113, Name = "H-Burst" },
            new BattleChipData { ID = 0x114, Name = "Z-Ball" },
            new BattleChipData { ID = 0x115, Name = "Z-Raton1" },
            new BattleChipData { ID = 0x116, Name = "Z-Raton2" },
            new BattleChipData { ID = 0x117, Name = "Z-Raton3" },
            new BattleChipData { ID = 0x118, Name = "O-Canon1" },
            new BattleChipData { ID = 0x119, Name = "O-Canon2" },
            new BattleChipData { ID = 0x11A, Name = "O-Canon3" },
            new BattleChipData { ID = 0x11B, Name = "M-Burst" },
            new BattleChipData { ID = 0x11C, Name = "O-Ball" },
            new BattleChipData { ID = 0x11D, Name = "O-Raton1" },
            new BattleChipData { ID = 0x11E, Name = "O-Raton2" },
            new BattleChipData { ID = 0x11F, Name = "O-Raton3" },
            new BattleChipData { ID = 0x120, Name = "Arrows" },
            new BattleChipData { ID = 0x121, Name = "UltraBmb" },
            new BattleChipData { ID = 0x122, Name = "LifeSrd1" },
            new BattleChipData { ID = 0x123, Name = "LifeSrd2" },
            new BattleChipData { ID = 0x124, Name = "LifeSrd3" },
            new BattleChipData { ID = 0x125, Name = "Punch" },
            new BattleChipData { ID = 0x126, Name = "Curse" },
            new BattleChipData { ID = 0x127, Name = "TimeBom+" },
            new BattleChipData { ID = 0x128, Name = "HvyStamp" },
            new BattleChipData { ID = 0x129, Name = "PoisPhar" },
            new BattleChipData { ID = 0x12A, Name = "Gater" },
            new BattleChipData { ID = 0x12B, Name = "GtsShoot" },
            new BattleChipData { ID = 0x12C, Name = "BigHeart" },
            new BattleChipData { ID = 0x12D, Name = "BodyGrd" },
            new BattleChipData { ID = 0x12E, Name = "2xHero" },
            new BattleChipData { ID = 0x12F, Name = "Darkness" }

        };

        public static BattleChipData GetChipNameByID(List<BattleChipData> chipmap, int chipID)
        {
            return chipmap.FirstOrDefault(x => x.ID == chipID);
        }

        public static int GetChipIDByName(List<BattleChipData> chipmap, string chipName)
        {
            return chipmap.FirstOrDefault(x => x.Name.ToLower() == chipName.ToLower()).ID;
        }

        public static Dictionary<string, List<string>> BN1ChipCodeMap = new Dictionary<string, List<string>>()
            {
                { "Cannon",   new List<string> { "A", "B", "C", "D", "E" } },
                { "HiCannon", new List<string> { "F", "G", "H", "I", "J" } },
                { "M-Cannon", new List<string> { "K", "L", "M", "N", "O" } },
                { "Sword",    new List<string> { "B", "K", "L", "P", "S" } },
                { "WideSwrd", new List<string> { "C", "K", "M", "N", "S" } },
                { "LongSwrd", new List<string> { "D", "E", "N", "O", "S" } },
                { "LilBomb",  new List<string> { "B", "D", "G", "O", "T" } },
                { "CrosBomb", new List<string> { "B", "D", "H", "J", "L" } },
                { "BigBomb",  new List<string> { "B", "G", "O", "S", "T" } },
                { "Spreader", new List<string> { "H", "I", "J", "K", "L" } },
                { "Bubbler",  new List<string> { "A", "K", "L", "P", "S" } },
                { "Heater",   new List<string> { "C", "F", "G", "K", "O" } },
                { "MiniBomb", new List<string> { "C", "E", "J", "L", "P" } },
                { "Shotgun",  new List<string> { "K", "M", "N", "Q", "R" } },
                { "Crossgun", new List<string> { "C", "E", "F", "J", "K" } },
                { "ShokWave", new List<string> { "C", "K", "L", "N", "P" } },
                { "SoniWave", new List<string> { "C", "D", "J", "M", "S" } },
                { "DynaWave", new List<string> { "C", "E", "M", "R", "S" } },
                { "FireTowr", new List<string> { "E", "F", "L", "M", "T" } },
                { "AquaTowr", new List<string> { "A", "C", "G", "H", "R" } },
                { "WoodTowr", new List<string> { "B", "C", "H", "K", "N" } },
                { "Quake1",   new List<string> { "A", "E", "H", "K", "Q" } },
                { "Quake2",   new List<string> { "B", "C", "I", "K", "Q" } },
                { "Quake3",   new List<string> { "C", "D", "H", "M", "Q" } },
                { "FireSwrd", new List<string> { "B", "F", "G", "N", "P" } },
                { "ElecSwrd", new List<string> { "E", "G", "L", "O", "S" } },
                { "AquaSwrd", new List<string> { "A", "M", "N", "O", "P" } },
                { "GutsPnch", new List<string> { "B", "H", "M", "N", "T" } },
                { "IcePunch", new List<string> { "B", "H", "M", "N", "T" } },
                { "FtrSwrd",  new List<string> { "B", "K", "L", "P", "S" } },
                { "Dash",     new List<string> { "B", "D", "G", "L", "O" } },
                { "KngtSwrd", new List<string> { "B", "C", "E", "G", "H" } },
                { "HeroSwrd", new List<string> { "B", "D", "F", "I", "J" } },
                { "MetGuard", new List<string> { "A", "C", "E", "G", "L" } },
                { "23",  new List<string> { "None", "None", "None", "None", "None" } },
                { "24",  new List<string> { "None", "None", "None", "None", "None" } },
                { "TriArrow", new List<string> { "A", "B", "C", "D", "E" } },
                { "TriSpear", new List<string> { "F", "G", "H", "I", "J" } },
                { "TriLance", new List<string> { "K", "L", "M", "N", "O" } },
                { "Typhoon",  new List<string> { "A", "B", "D", "E", "G" } },
                { "Huricane", new List<string> { "G", "I", "J", "K", "L" } },
                { "Cyclone",  new List<string> { "E", "F", "G", "H", "I" } },
                { "Howitzer", new List<string> { "A", "C", "G", "H", "O" } },
                { "Thunder1", new List<string> { "A", "E", "G", "H", "S" } },
                { "Thunder2", new List<string> { "B", "C", "F", "I", "L" } },
                { "Thunder3", new List<string> { "D", "F", "G", "K", "N" } },
                { "2F",  new List<string> { "None", "None", "None", "None", "None" } },
                { "30",  new List<string> { "None", "None", "None", "None", "None" } },
                { "Snakegg1", new List<string> { "B", "E", "G", "M", "N" } },
                { "Snakegg2", new List<string> { "C", "E", "H", "N", "P" } },
                { "Snakegg3", new List<string> { "A", "C", "F", "L", "S" } },
                { "Hammer",   new List<string> { "A", "F", "I", "M", "Q" } },
                { "35",  new List<string> { "None", "None", "None", "None", "None" } },
                { "36",  new List<string> { "None", "None", "None", "None", "None" } },
                { "Bodyburn", new List<string> { "E", "F", "K", "M", "N" } },
                { "38",  new List<string> { "None", "None", "None", "None", "None" } },
                { "39",  new List<string> { "None", "None", "None", "None", "None" } },
                { "Ratton1",  new List<string> { "A", "B", "C", "D", "E" } },
                { "Ratton2",  new List<string> { "F", "G", "H", "I", "J" } },
                { "Ratton3",  new List<string> { "K", "L", "M", "N", "O" } },
                { "Lockon1",  new List<string> { "C", "D", "H", "I", "L" } },
                { "Lockon2",  new List<string> { "B", "E", "G", "H", "M" } },
                { "Lockon3",  new List<string> { "A", "D", "K", "N", "O" } },
                { "X-Panel1", new List<string> { "B", "D", "G", "L", "S" } },
                { "X-Panel3", new List<string> { "B", "D", "G", "L", "S" } },
                { "42",  new List<string> { "None", "None", "None", "None", "None" } },
                { "Recov10",  new List<string> { "A", "C", "E", "G", "L" } },
                { "Recov30",  new List<string> { "A", "C", "E", "G", "L" } },
                { "Recov50",  new List<string> { "A", "C", "E", "G", "L" } },
                { "Recov80",  new List<string> { "A", "C", "E", "G", "L" } },
                { "Recov120", new List<string> { "A", "C", "E", "G", "L" } },
                { "Recov150", new List<string> { "A", "C", "E", "G", "L" } },
                { "Recov200", new List<string> { "A", "C", "E", "G", "L" } },
                { "Recov300", new List<string> { "A", "C", "E", "G", "L" } },
                { "4B",  new List<string> { "None", "None", "None", "None", "None" } },
                { "Steal",    new List<string> { "A", "E", "L", "P", "S" } },
                { "4D",  new List<string> { "None", "None", "None", "None", "None" } },
                { "4E",  new List<string> { "None", "None", "None", "None", "None" } },
                { "Geddon1",  new List<string> { "F", "H", "J", "L", "N" } },
                { "Geddon2",  new List<string> { "A", "B", "E", "I", "K" } },
                { "51",  new List<string> { "None", "None", "None", "None", "None" } },
                { "Escape",   new List<string> { "F", "H", "J", "L", "N" } },
                { "Interupt", new List<string> { "F", "H", "J", "L", "N" } },
                { "LifeAura", new List<string> { "A", "H", "K", "M", "P" } },
                { "AquaAura", new List<string> { "D", "E", "L", "R", "S" } },
                { "FireAura", new List<string> { "B", "G", "I", "N", "T" } },
                { "WoodAura", new List<string> { "C", "F", "J", "O", "Q" } },
                { "Repair",   new List<string> { "A", "G", "H", "K", "S" } },
                { "59",  new List<string> { "None", "None", "None", "None", "None" } },
                { "5A",  new List<string> { "None", "None", "None", "None", "None" } },
                { "Cloud",    new List<string> { "B", "G", "H", "O", "R" } },
                { "Cloudier", new List<string> { "A", "D", "I", "M", "P" } },
                { "Cloudest", new List<string> { "C", "F", "J", "K", "O" } },
                { "IceCube",  new List<string> { "A", "C", "I", "L", "M" } },
                { "RockCube", new List<string> { "B", "E", "G", "M", "O" } },
                { "60",  new List<string> { "None", "None", "None", "None", "None" } },
                { "TimeBom1", new List<string> { "E", "G", "J", "L", "Q" } },
                { "TimeBom2", new List<string> { "C", "F", "J", "L", "S" } },
                { "TimeBom3", new List<string> { "A", "B", "G", "O", "P" } },
                { "Invis1",   new List<string> { "I", "J", "L", "O", "Q" } },
                { "Invis2",   new List<string> { "A", "C", "F", "J", "M" } },
                { "Invis3",   new List<string> { "B", "D", "H", "K", "N" } },
                { "IronBody", new List<string> { "C", "D", "L", "Q", "R" } },
                { "68",  new List<string> { "None", "None", "None", "None", "None" } },
                { "Remobit1", new List<string> { "A", "C", "F", "N", "O" } },
                { "Remobit2", new List<string> { "B", "D", "E", "H", "I" } },
                { "Remobit3", new List<string> { "G", "J", "K", "P", "Q" } },
                { "BstrGard", new List<string> { "A", "G", "K", "N", "R" } },
                { "BstrBomb", new List<string> { "D", "H", "J", "O", "T" } },
                { "BstrSwrd", new List<string> { "B", "E", "L", "P", "S" } },
                { "BstrPnch", new List<string> { "C", "F", "I", "M", "Q" } },
                { "RingZap1", new List<string> { "G", "H", "M", "N", "P" } },
                { "RingZap2", new List<string> { "C", "E", "G", "J", "L" } },
                { "RingZap3", new List<string> { "A", "B", "O", "R", "T" } },
                { "Candle1",  new List<string> { "C", "F", "I", "P", "S" } },
                { "Candle2",  new List<string> { "B", "E", "G", "J", "L" } },
                { "Candle3",  new List<string> { "A", "D", "H", "K", "M" } },
                { "SloGauge", new List<string> { "H", "K", "N", "O", "Q" } },
                { "FstGauge", new List<string> { "A", "C", "E", "L", "N" } },
                { "78",  new List<string> { "None", "None", "None", "None", "None" } },
                { "Drain1",   new List<string> { "A", "B", "D", "K", "O" } },
                { "Drain2",   new List<string> { "A", "C", "H", "N", "T" } },
                { "Drain3",   new List<string> { "A", "E", "F", "L", "Q" } },
                { "Mine1",    new List<string> { "G", "H", "M", "N", "P" } },
                { "Mine2",    new List<string> { "C", "E", "G", "J", "L" } },
                { "Mine3",    new List<string> { "A", "B", "O", "R", "T" } },
                { "Gaia1",    new List<string> { "C", "D", "L", "O", "T" } },
                { "Gaia2",    new List<string> { "C", "F", "K", "P", "S" } },
                { "Gaia3",    new List<string> { "C", "G", "M", "N", "T" } },
                { "BblWrap1", new List<string> { "C", "E", "G", "I", "M" } },
                { "BblWrap2", new List<string> { "D", "F", "H", "K", "N" } },
                { "BblWrap3", new List<string> { "A", "B", "L", "Q", "R" } },
                { "Wave",     new List<string> { "A", "D", "I", "L", "M" } },
                { "RedWave",  new List<string> { "B", "E", "J", "N", "P" } },
                { "BigWave",  new List<string> { "C", "H", "K", "L", "Q" } },
                { "Muramasa", new List<string> { "C", "E", "G", "J", "K" } },
                { "Dropdown", new List<string> { "A", "B", "O", "R", "T" } },
                { "Popup",    new List<string> { "C", "D", "H", "K", "N" } },
                { "Dynamyt1", new List<string> { "B", "G", "O", "Q", "S" } },
                { "Dynamyt2", new List<string> { "A", "C", "K", "M", "N" } },
                { "Dynamyt3", new List<string> { "G", "K", "M", "O", "P" } },
                { "Anubis",   new List<string> { "C", "L", "N", "Q", "T" } },
                { "8F",  new List<string> { "None", "None", "None", "None", "None" } },
                { "90",  new List<string> { "None", "None", "None", "None", "None" } },
                { "IronShld", new List<string> { "A", "B", "O", "R", "T" } },
                { "LeafShld", new List<string> { "C", "D", "F", "K", "Q" } },
                { "Barrier",  new List<string> { "D", "F", "M", "R", "S" } },
                { "PharoMan", new List<string> { "P" } },
                { "PharoMn2", new List<string> { "P" } },
                { "PharoMn3", new List<string> { "P" } },
                { "ShadoMan", new List<string> { "S" } },
                { "ShadoMn2", new List<string> { "S" } },
                { "ShadoMn3", new List<string> { "S" } },
                { "9A",  new List<string> { "None" } },
                { "9B",  new List<string> { "None" } },
                { "9C",  new List<string> { "None" } },
                { "MagicMan", new List<string> { "M" } },
                { "MagicMn2", new List<string> { "M" } },
                { "MagicMn3", new List<string> { "M" } },
                { "Roll",     new List<string> { "R" } },
                { "Roll2",    new List<string> { "R" } },
                { "Roll3",    new List<string> { "R" } },
                { "GutsMan",  new List<string> { "G" } },
                { "GutsMan2", new List<string> { "G" } },
                { "GutsMan3", new List<string> { "G" } },
                { "ProtoMan", new List<string> { "B" } },
                { "ProtoMn2", new List<string> { "B" } },
                { "ProtoMn3", new List<string> { "B" } },
                { "WoodMan",  new List<string> { "W" } },
                { "WoodMan2", new List<string> { "W" } },
                { "WoodMan3", new List<string> { "W" } },
                { "FireMan",  new List<string> { "F" } },
                { "FireMan2", new List<string> { "F" } },
                { "FireMan3", new List<string> { "F" } },
                { "NumbrMan", new List<string> { "N" } },
                { "NumbrMn2", new List<string> { "N" } },
                { "NumbrMn3", new List<string> { "N" } },
                { "StoneMan", new List<string> { "S" } },
                { "StoneMn2", new List<string> { "S" } },
                { "StoneMn3", new List<string> { "S" } },
                { "IceMan",   new List<string> { "I" } },
                { "IceMan2",  new List<string> { "I" } },
                { "IceMan3",  new List<string> { "I" } },
                { "SkullMan", new List<string> { "S" } },
                { "SkullMn2", new List<string> { "S" } },
                { "SkullMn3", new List<string> { "S" } },
                { "ColorMan", new List<string> { "C" } },
                { "ColorMn2", new List<string> { "C" } },
                { "ColorMn3", new List<string> { "C" } },
                { "BombMan",  new List<string> { "B" } },
                { "BombMan2", new List<string> { "B" } },
                { "BombMan3", new List<string> { "B" } },
                { "SharkMan", new List<string> { "S" } },
                { "SharkMn2", new List<string> { "S" } },
                { "SharkMn3", new List<string> { "S" } },
                { "ElecMan",  new List<string> { "E" } },
                { "ElecMan2", new List<string> { "E" } },
                { "ElecMan3", new List<string> { "E" } },
                { "Bass",     new List<string> { "F" } },
                { "C8",  new List<string> { "None" } },
                { "C9",  new List<string> { "None" } },
                { "Z-Canon1", new List<string> { "None" } },
                { "Z-Canon2", new List<string> { "None" } },
                { "Z-Canon3", new List<string> { "None" } },
                { "Z-Spread", new List<string> { "None" } },
                { "Z-Raton1", new List<string> { "None" } },
                { "Z-Raton2", new List<string> { "None" } },
                { "Z-Raton3", new List<string> { "None" } },
                { "Z-Arrow",  new List<string> { "None" } },
                { "Z-Spear",  new List<string> { "None" } },
                { "Z-Lance",  new List<string> { "None" } },
                { "O-Canon1", new List<string> { "None" } },
                { "O-Canon2", new List<string> { "None" } },
                { "O-Canon3", new List<string> { "None" } },
                { "O-Spread", new List<string> { "None" } },
                { "O-Raton1", new List<string> { "None" } },
                { "O-Raton2", new List<string> { "None" } },
                { "O-Raton3", new List<string> { "None" } },
                { "O-Arrow",  new List<string> { "None" } },
                { "O-Spear",  new List<string> { "None" } },
                { "O-Lance",  new List<string> { "None" } },
                { "B-Bomb",   new List<string> { "None" } },
                { "B-Sword",  new List<string> { "None" } },
                { "B-Wave",   new List<string> { "None" } },
                { "B-Quake",  new List<string> { "None" } },
                { "S-Bomb",   new List<string> { "None" } },
                { "S-Sword",  new List<string> { "None" } },
                { "S-Wave",   new List<string> { "None" } },
                { "S-Quake",  new List<string> { "None" } },
                { "PwrCanon", new List<string> { "None" } },
                { "HvyStamp", new List<string> { "None" } },
                { "BgStrait", new List<string> { "None" } },
                { "BloodSuk", new List<string> { "None" } },
                { "Storm",    new List<string> { "None" } },
                { "GtsShoot", new List<string> { "None" } },
                { "LifeSavr", new List<string> { "None" } },
                { "2xHero",   new List<string> { "None" } },
                { "EE",  new List<string> { "None" } },
                { "EF",  new List<string> { "None" } }
            };
        public static Dictionary<string, List<string>> BN2ChipCodeMap = new Dictionary<string, List<string>>()
        {
            { "Cannon", new List<string> { "A", "B", "C", "D", "E", "*" } },
            { "HiCannon", new List<string> { "C", "D", "E", "F", "G", "*" } },
            { "M-Cannon", new List<string> { "E", "F", "G", "H", "I", "*" } },
            { "Shotgun", new List<string> { "B", "F", "H", "J", "N", "*" } },
            { "V-Gun", new List<string> { "A", "F", "G", "L", "P", "*" } },
            { "CrossGun", new List<string> { "H", "J", "M", "Q", "S", "*" } },
            { "Spreader", new List<string> { "M", "N", "O", "P", "Q", "*" } },
            { "Bubbler", new List<string> { "B", "G", "H", "P", "R", "None" } },
            { "Bub-V", new List<string> { "C", "D", "J", "N", "S", "None" } },
            { "BubCross", new List<string> { "K", "O", "P", "T", "V", "None" } },
            { "BubSprd", new List<string> { "E", "F", "I", "L", "M", "None" } },
            { "HeatShot", new List<string> { "B", "G", "H", "P", "R", "None" } },
            { "Heat-V", new List<string> { "C", "D", "J", "N", "S", "None" } },
            { "HeatCros", new List<string> { "K", "O", "P", "T", "V", "None" } },
            { "HeatSprd", new List<string> { "E", "F", "I", "L", "M", "None" } },
            { "MiniBomb", new List<string> { "B", "E", "G", "L", "O", "*" } },
            { "LilBomb", new List<string> { "F", "J", "O", "Q", "T", "*" } },
            { "CrosBomb", new List<string> { "D", "J", "O", "Q", "T", "None" } },
            { "BigBomb", new List<string> { "O", "Q", "T", "V", "Y", "*" } },
            { "TreeBom1", new List<string> { "B", "G", "H", "P", "R", "*" } },
            { "TreeBom2", new List<string> { "C", "D", "J", "N", "S", "*" } },
            { "TreeBom3", new List<string> { "K", "O", "P", "T", "V", "*" } },
            { "Sword", new List<string> { "A", "K", "L", "S", "Y", "*" } },
            { "WideSwrd", new List<string> { "A", "C", "L", "Q", "Y", "*" } },
            { "LongSwrd", new List<string> { "A", "I", "L", "O", "Y", "None" } },
            { "FireSwrd", new List<string> { "F", "H", "N", "R", "U", "None" } },
            { "AquaSwrd", new List<string> { "A", "H", "N", "R", "W", "None" } },
            { "ElecSwrd", new List<string> { "E", "H", "N", "R", "V", "*" } },
            { "FireBlde", new List<string> { "F", "H", "P", "R", "Z", "*" } },
            { "AquaBlde", new List<string> { "A", "F", "J", "R", "Z", "*" } },
            { "ElecBlde", new List<string> { "E", "F", "M", "N", "R", "*" } },
            { "StepSwrd", new List<string> { "D", "H", "M", "Q", "U", "*" } },
            { "Muramasa", new List<string> { "N", "O", "T", "U", "W", "None" } },
            { "CustSwrd", new List<string> { "B", "G", "K", "Q", "T", "None" } },
            { "Kunai1", new List<string> { "E", "I", "L", "P", "S", "None" } },
            { "Kunai2", new List<string> { "D", "F", "J", "Q", "R", "None" } },
            { "Kunai3", new List<string> { "C", "G", "H", "K", "N", "None" } },
            { "Slasher ", new List<string> { "A", "D", "H", "L", "Q", "*" } },
            { "Shockwav", new List<string> { "H", "J", "L", "R", "U", "None" } },
            { "Sonicwav", new List<string> { "E", "I", "M", "S", "W", "None" } },
            { "Dynawave", new List<string> { "G", "N", "Q", "T", "V", "None" } },
            { "Quake1", new List<string> { "A", "M", "P", "Q", "W", "None" } },
            { "Quake2", new List<string> { "B", "G", "N", "Q", "W", "None" } },
            { "Quake3", new List<string> { "C", "E", "O", "Q", "W", "None" } },
            { "GutPunch", new List<string> { "B", "D", "H", "K", "N", "None" } },
            { "ColdPnch", new List<string> { "B", "D", "L", "P", "S", "None" } },
            { "Atk+20", new List<string> { "None", "None", "None", "None", "None", "*" } },
            { "Atk+30", new List<string> { "None", "None", "None", "None", "None", "*" } },
            { "Navi+40", new List<string> { "None", "None", "None", "None", "None", "*" } },
            { "DashAtk", new List<string> { "B", "D", "G", "J", "L", "*" } },
            { "Wrecker", new List<string> { "O", "Q", "S", "U", "W", "None" } },
            { "CannBall", new List<string> { "O", "P", "Q", "R", "S", "*" } },
            { "DoubNdl", new List<string> { "A", "C", "F", "I", "J", "None" } },
            { "TripNdl", new List<string> { "C", "I", "M", "T", "V", "None" } },
            { "QuadNdl", new List<string> { "C", "H", "I", "P", "U", "None" } },
            { "Trident", new List<string> { "E", "I", "K", "O", "T", "None" } },
            { "Ratton1", new List<string> { "H", "I", "J", "K", "L", "*" } },
            { "Ratton2", new List<string> { "J", "K", "L", "M", "N", "*" } },
            { "Ratton3", new List<string> { "L", "M", "N", "O", "P", "*" } },
            { "FireRat", new List<string> { "B", "F", "G", "H", "R", "*" } },
            { "Tornado", new List<string> { "E", "J", "L", "M", "Q", "None" } },
            { "Twister", new List<string> { "N", "O", "T", "U", "Y", "None" } },
            { "Blower", new List<string> { "P", "R", "T", "W", "Z", "None" } },
            { "Burner", new List<string> { "A", "B", "F", "L", "S", "None" } },
            { "ZapRing1", new List<string> { "A", "M", "P", "Q", "W", "*" } },
            { "ZapRing2", new List<string> { "B", "G", "N", "R", "S", "None" } },
            { "ZapRing3", new List<string> { "C", "E", "O", "T", "Z", "None" } },
            { "Spice1", new List<string> { "A", "C", "G", "Q", "T", "None" } },
            { "Spice2", new List<string> { "B", "E", "H", "J", "N", "None" } },
            { "Spice3", new List<string> { "D", "K", "M", "P", "Q", "None" } },
            { "Satelit1", new List<string> { "G", "O", "Q", "U", "W", "None" } },
            { "Satelit2", new List<string> { "H", "J", "K", "P", "R", "None" } },
            { "Satelit3", new List<string> { "L", "S", "T", "Y", "Z", "None" } },
            { "Yo-Yo1", new List<string> { "C", "E", "R", "T", "V", "None" } },
            { "Yo-Yo2", new List<string> { "A", "G", "J", "K", "N", "None" } },
            { "Yo-Yo3", new List<string> { "D", "I", "M", "S", "Y", "None" } },
            { "MagBomb1", new List<string> { "F", "G", "J", "M", "N", "*" } },
            { "MagBomb2", new List<string> { "B", "D", "I", "R", "T", "*" } },
            { "MagBomb3", new List<string> { "H", "K", "O", "Q", "S", "*" } },
            { "Meteor9", new List<string> { "C", "E", "L", "S", "V", "*" } },
            { "Meteor12", new List<string> { "A", "C", "F", "J", "W", "*" } },
            { "Meteor15", new List<string> { "D", "G", "H", "R", "Z", "*" } },
            { "Meteor18", new List<string> { "B", "G", "I", "K", "O", "*" } },
            { "Hammer", new List<string> { "R", "T", "U", "V", "Z", "None" } },
            { "CrsShld1", new List<string> { "A", "O", "P", "S", "Z", "None" } },
            { "CrsShld2", new List<string> { "A", "O", "P", "T", "V", "None" } },
            { "CrsShld3", new List<string> { "A", "O", "P", "U", "W", "None" } },
            { "TimeBom1", new List<string> { "C", "G", "K", "M", "Z", "None" } },
            { "TimeBom2", new List<string> { "F", "G", "K", "O", "Z", "None" } },
            { "TimeBom3", new List<string> { "E", "G", "K", "P", "Z", "None" } },
            { "LilCloud", new List<string> { "C", "G", "I", "K", "N", "None" } },
            { "MedCloud", new List<string> { "D", "H", "J", "L", "O", "None" } },
            { "BigCloud", new List<string> { "Q", "R", "T", "U", "W", "None" } },
            { "Mine", new List<string> { "L", "N", "R", "S", "V", "None" } },
            { "FrntSnsr", new List<string> { "H", "M", "Q", "R", "T", "None" } },
            { "DblSnsr", new List<string> { "E", "J", "P", "W", "Y", "None" } },
            { "Remobit1", new List<string> { "E", "G", "J", "K", "N", "None" } },
            { "Remobit2", new List<string> { "B", "F", "I", "R", "U", "None" } },
            { "Remobit3", new List<string> { "A", "L", "M", "T", "Y", "None" } },
            { "AquaBall", new List<string> { "A", "B", "Q", "T", "W", "None" } },
            { "ElecBall", new List<string> { "E", "H", "J", "K", "V", "None" } },
            { "HeatBall", new List<string> { "C", "F", "R", "S", "U", "None" } },
            { "Geyser", new List<string> { "A", "B", "D", "L", "S", "None" } },
            { "LavaDrag", new List<string> { "F", "G", "O", "R", "Y", "None" } },
            { "GodStone", new List<string> { "E", "I", "L", "Q", "U", "None" } },
            { "OldWood", new List<string> { "C", "M", "S", "T", "W", "None" } },
            { "PoisMask", new List<string> { "D", "S", "U", "W", "Z", "None" } },
            { "PoisFace", new List<string> { "P", "Q", "U", "W", "Y", "None" } },
            { "Whirlpl", new List<string> { "A", "C", "E", "G", "I", "None" } },
            { "Blckhole", new List<string> { "B", "D", "F", "H", "J", "None" } },
            { "Guard", new List<string> { "None", "None", "None", "None", "None", "*" } },
            { "Barrier", new List<string> { "B", "E", "L", "S", "T", "*" } },
            { "PanlOut1", new List<string> { "A", "B", "D", "L", "S", "*" } },
            { "PanlOut3", new List<string> { "C", "E", "N", "R", "Y", "*" } },
            { "LineOut", new List<string> { "F", "H", "J", "Q", "T", "*" } },
            { "Lance", new List<string> { "O", "P", "T", "V", "Y", "*" } },
            { "ZeusHamr", new List<string> { "J", "K", "O", "V", "Z", "None" } },
            { "BrnzFist", new List<string> { "B", "N", "O", "R", "S", "None" } },
            { "SilvFist", new List<string> { "E", "I", "L", "S", "V", "None" } },
            { "GoldFist", new List<string> { "D", "G", "L", "O", "Z", "None" } },
            { "VarSwrd", new List<string> { "B", "L", "N", "T", "Z" } },
            { "Recov10", new List<string> { "A", "C", "E", "G", "L", "*" } },
            { "Recov30", new List<string> { "B", "D", "F", "H", "M", "*" } },
            { "Recov50", new List<string> { "C", "E", "G", "I", "N", "*" } },
            { "Recov80", new List<string> { "D", "F", "H", "J", "O", "*" } },
            { "Recov120", new List<string> { "O", "Q", "S", "U", "W", "None" } },
            { "Recov150", new List<string> { "N", "P", "R", "T", "V", "None" } },
            { "Recov200", new List<string> { "M", "N", "U", "V", "W", "None" } },
            { "Recov300", new List<string> { "O", "R", "V", "W", "Z", "None" } },
            { "PanlGrab", new List<string> { "B", "H", "K", "L", "P", "*" } },
            { "AreaGrab", new List<string> { "E", "L", "R", "S", "Z", "*" } },
            { "GrabRvng", new List<string> { "A", "L", "P", "S", "W", "None" } },
            { "Geddon1", new List<string> { "C", "K", "L", "Q", "S", "None" } },
            { "Geddon2", new List<string> { "J", "M", "R", "T", "Z", "None" } },
            { "Geddon3", new List<string> { "E", "J", "N", "P", "Y", "None" } },
            { "Catcher", new List<string> { "F", "I", "J", "N", "T", "*" } },
            { "Mindbndr", new List<string> { "D", "I", "M", "N", "T", "None" } },
            { "Escape", new List<string> { "F", "H", "J", "L", "N", "None" } },
            { "AirShoes", new List<string> { "A", "J", "O", "V", "Z", "*" } },
            { "Repair", new List<string> { "A", "C", "E", "L", "P", "*" } },
            { "Candle1", new List<string> { "C", "F", "I", "M", "V", "*" } },
            { "Candle2", new List<string> { "A", "G", "J", "L", "T", "*" } },
            { "Candle3", new List<string> { "B", "E", "H", "N", "W", "*" } },
            { "RockCube", new List<string> { "B", "D", "G", "M", "V", "*" } },
            { "Prism", new List<string> { "B", "C", "L", "N", "Q", "*" } },
            { "Guardian", new List<string> { "O", "P", "U", "V", "Z", "None" } },
            { "Wind", new List<string> { "G", "J", "O", "Q", "T", "*" } },
            { "Fan", new List<string> { "A", "G", "L", "N", "Y", "*" } },
            { "Anubis", new List<string> { "H", "K", "M", "U", "W", "None" } },
            { "SloGauge", new List<string> { "None", "None", "None", "None", "None", "*" } },
            { "FstGauge", new List<string> { "None", "None", "None", "None", "None", "*" } },
            { "FullCust", new List<string> { "None", "None", "None", "None", "None", "*" } },
            { "Invis1", new List<string> { "A", "F", "L", "R", "U", "*" } },
            { "Invis2", new List<string> { "B", "H", "M", "Q", "V", "*" } },
            { "Invis3", new List<string> { "C", "G", "K", "P", "W", "*" } },
            { "DropDown", new List<string> { "A", "C", "F", "Q", "S", "*" } },
            { "PopUp", new List<string> { "D", "I", "J", "T", "W", "None" } },
            { "StoneBod", new List<string> { "C", "E", "S", "T", "W", "*" } },
            { "Shadow1", new List<string> { "B", "G", "H", "L", "R", "None" } },
            { "Shadow2", new List<string> { "D", "E", "J", "M", "T", "None" } },
            { "Shadow3", new List<string> { "C", "F", "K", "N", "V", "None" } },
            { "UnderSht", new List<string> { "H", "J", "N", "R", "W", "*" } },
            { "BblWrap", new List<string> { "I", "J", "Q", "R", "W", "None" } },
            { "LeafShld", new List<string> { "A", "D", "R", "S", "W", "None" } },
            { "AquaAura", new List<string> { "A", "E", "I", "M", "Q", "*" } },
            { "FireAura", new List<string> { "B", "F", "J", "N", "R", "*" } },
            { "WoodAura", new List<string> { "C", "G", "K", "O", "S", "None" } },
            { "ElecAura", new List<string> { "D", "H", "L", "P", "T", "None" } },
            { "LifeAur1", new List<string> { "B", "G", "I", "O", "Q", "None" } },
            { "LifeAur2", new List<string> { "D", "F", "J", "N", "R", "None" } },
            { "LifeAur3", new List<string> { "E", "None", "K", "None", "T", "None" } },
            { "MagLine", new List<string> { "A", "E", "I", "M", "Q", "*" } },
            { "LavaLine", new List<string> { "A", "F", "J", "M", "R", "*" } },
            { "IceLine", new List<string> { "B", "E", "J", "N", "Q", "*" } },
            { "GrassLne", new List<string> { "B", "F", "I", "N", "R", "*" } },
            { "LavaStge", new List<string> { "D", "H", "M", "U", "V", "*" } },
            { "IceStage", new List<string> { "A", "C", "E", "I", "S", "*" } },
            { "GrassStg", new List<string> { "B", "D", "H", "P", "R", "None" } },
            { "HolyPanl", new List<string> { "C", "E", "H", "L", "R", "*" } },
            { "Jealosy", new List<string> { "E", "J", "O", "R", "U", "*" } },
            { "AntiFire", new List<string> { "F", "K", "L", "P", "T", "None" } },
            { "AntiElec", new List<string> { "E", "H", "N", "U", "Y", "None" } },
            { "AntiWatr", new List<string> { "A", "D", "Q", "W", "Z", "None" } },
            { "AntiDmg", new List<string> { "C", "J", "M", "R", "S", "None" } },
            { "AntiSwrd", new List<string> { "D", "H", "I", "M", "T", "None" } },
            { "AntiNavi", new List<string> { "K", "L", "O", "T", "X", "None" } },
            { "AntiRecv", new List<string> { "B", "D", "M", "P", "W", "None" } },
            { "Atk+10", new List<string> { "None", "None", "None", "None", "None", "*" } },
            { "Fire+40", new List<string> { "None", "None", "None", "None", "None", "*" } },
            { "Aqua+40", new List<string> { "None", "None", "None", "None", "None", "*" } },
            { "Wood+40", new List<string> { "None", "None", "None", "None", "None", "*" } },
            { "Elec+40", new List<string> { "None", "None", "None", "None", "None", "*" } },
            { "Navi+20", new List<string> { "None", "None", "None", "None", "None", "*" } },
            { "Roll", new List<string> { "R", "*" } },
            { "Roll V2", new List<string> { "R", "*" } },
            { "Roll V3", new List<string> { "R", "None" } },
            { "GutsMan ", new List<string> { "G", "*" } },
            { "GutsMan V2", new List<string> { "G", "None" } },
            { "GutsMan V3", new List<string> { "G", "None" } },
            { "ProtoMan", new List<string> { "B", "*" } },
            { "ProtoMn V2", new List<string> { "B", "None" } },
            { "ProtoMn V3", new List<string> { "B", "None" } },
            { "AirMan", new List<string> { "A", "*" } },
            { "AirMan V2", new List<string> { "A", "*" } },
            { "AirMan V3", new List<string> { "A", "*" } },
            { "QuickMan", new List<string> { "Q", "*" } },
            { "QuickMn V2", new List<string> { "Q", "*" } },
            { "QuickMn V3", new List<string> { "Q", "*" } },
            { "CutMan", new List<string> { "C", "*" } },
            { "CutMan V2", new List<string> { "C", "*" } },
            { "CutMan V3", new List<string> { "C", "*" } },
            { "ShadoMan", new List<string> { "S", "*" } },
            { "ShadoMn V2", new List<string> { "S", "None" } },
            { "ShadoMn V3", new List<string> { "S", "None" } },
            { "KnightMn", new List<string> { "K", "*" } },
            { "KnghtMn V2", new List<string> { "K", "None" } },
            { "KnghtMn V3", new List<string> { "K", "None" } },
            { "MagnetMn", new List<string> { "M", "*" } },
            { "MagntMn V2", new List<string> { "M", "None" } },
            { "MagntMn V3", new List<string> { "M", "None" } },
            { "FreezeMn", new List<string> { "F", "*" } },
            { "FrzMan V2", new List<string> { "F", "None" } },
            { "FrzMan V3", new List<string> { "F", "None" } },
            { "HeatMan", new List<string> { "H", "*" } },
            { "HeatMan V2", new List<string> { "H", "None" } },
            { "HeatMan V3", new List<string> { "H", "None" } },
            { "ToadMan", new List<string> { "T", "*" } },
            { "ToadMan V2", new List<string> { "T", "None" } },
            { "ToadMan V3", new List<string> { "T", "None" } },
            { "ThunMan", new List<string> { "T", "*" } },
            { "ThunMan V2", new List<string> { "T", "None" } },
            { "ThunMan V3", new List<string> { "T", "None" } },
            { "SnakeMan", new List<string> { "S", "*" } },
            { "SnakeMn V2", new List<string> { "S", "None" } },
            { "SnakeMn V3", new List<string> { "S", "None" } },
            { "GateMan", new List<string> { "G", "*" } },
            { "GateMan V2", new List<string> { "G", "None" } },
            { "GateMan V3", new List<string> { "G", "None" } },
            { "PlanetMn", new List<string> { "P", "None" } },
            { "PlnetMn V2", new List<string> { "P", "None" } },
            { "PlnetMn V3", new List<string> { "P", "None" } },
            { "NapalmMnV3", new List<string> { "N", "None" } },
            { "NaplmMn V2", new List<string> { "N", "None" } },
            { "NaplmMn V3", new List<string> { "N", "None" } },
            { "PharoMan", new List<string> { "P", "None" } },
            { "PharoMn V2", new List<string> { "P", "None" } },
            { "PharoMn V3", new List<string> { "P", "None" } },
            { "Bass", new List<string> { "F", "None" } },
            { "Bass V2", new List<string> { "F", "None" } },
            { "Bass V3", new List<string> { "X", "None" } },
            { "BgRedWav", new List<string> { "F", "H", "P", "R", "S", "None" } },
            { "FreezBom", new List<string> { "A", "I", "J", "Q", "U", "None" } },
            { "Sparker", new List<string> { "C", "E", "G", "K", "V", "None" } },
            { "GaiaSwrd", new List<string> { "D", "L", "N", "W", "Y", "None" } },
            { "BlkBomb", new List<string> { "B", "F", "G", "P", "R", "None" } },
            { "FtrSword", new List<string> { "A", "I", "L", "S", "Y", "*" } },
            { "KngtSwrd", new List<string> { "F", "J", "K", "M", "Q", "None" } },
            { "HeroSwrd", new List<string> { "E", "N", "O", "T", "None", "None" } },
            { "Meteors", new List<string> { "B", "H", "O", "R", "V", "None" } },
            { "Poltrgst", new List<string> { "E", "P", "R", "U", "W", "None" } },
            { "FireGspl", new List<string> { "X", "None", "None", "None", "None", "None" } },
            { "AquaGspl", new List<string> { "X", "None", "None", "None", "None", "None" } },
            { "ElecGspl", new List<string> { "X", "None", "None", "None", "None", "None" } },
            { "WoodGspl", new List<string> { "X", "None", "None", "None", "None", "None" } },
            { "GateSP", new List<string> { "G", "None", "None", "None", "None", "None" } },
            { "10A", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "10B", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "10C", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "10D", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "Snctuary", new List<string> { "A", "C", "E", "L", "S", "None" } },
            { "10F", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "Z-Canon1", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "Z-Canon2", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "Z-Canon3", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "H-Burst", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "Z-Ball", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "Z-Raton1", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "Z-Raton2", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "Z-Raton3", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "O-Canon1", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "O-Canon2", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "O-Canon3", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "M-Burst", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "O-Ball", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "O-Raton1", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "O-Raton2", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "O-Raton3", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "Arrows", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "UltraBmb", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "LifeSrd1", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "LifeSrd2", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "LifeSrd3", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "Punch", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "Curse", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "TimeBom+", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "HvyStamp", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "PoisPhar", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "Gater", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "GtsShoot", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "BigHeart", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "BodyGrd", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "2xHero", new List<string> { "None", "None", "None", "None", "None", "None" } },
            { "Darkness", new List<string> { "None", "None", "None", "None", "None", "None" } }
        };

        public List<BattleChipData> GenerateChipEntries()
        {
            List<BattleChipData> chipEntries = new List<BattleChipData>();

            // Generate chip entries for each chip name and associated codes
            foreach (var kvp in BN1ChipCodeMap)
            {
                string chipName = kvp.Key;
                List<string> chipCodes = kvp.Value;

                foreach (var chipCode in chipCodes)
                {
                    BattleChipData chipEntry = new BattleChipData
                    {
                        ID = GetChipIDByName(BN1ChipNameMap, chipName),
                        Name = chipName,
                        Code = chipCode,
                        Quantity = 0 // Set the initial quantity to 0
                    };

                    chipEntries.Add(chipEntry);
                }
            }
            return chipEntries;
        }

    }
}

